<?php
// +----------------------------------------------------------------------
// | bronet [ 以客户为中心 以奋斗者为本 ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013-2017 http://www.bronet.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: Powerless < wzxaini9@gmail.com>
// +----------------------------------------------------------------------

namespace app\user\controller;

use cmf\controller\AdminBaseController;
use think\Db;

error_reporting(E_ERROR | E_PARSE);

/**
 * 患者中心名称及诊断管理
 * Class MedicalHistoryController
 * @package app\user\controller
 */
class CenterDiagnoseController extends AdminBaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $user_id = input('user_id');
        $user = Db::name('user')->find($user_id);
        $this->user = $user;
        $this->admin_id = session('ADMIN_ID');
        $this->assign('user', $user);
    }

    /**
     * 数据列表
     * @return mixed
     */
    public function index()
    {
        $request = input('request.');
        if (!empty($request['user_nickname'])) {
            $where['user_nickname'] = ['like', "%" . $request['user_nickname'] . "%"];
        }
        if (!empty($request['title'])) {
            $where['title'] = $request['title'];
        }
        if (!empty($request['start_time']) && !empty($request['end_time'])) {
            $start_time = strtotime($request['start_time']);
            $end_time = strtotime($request['end_time']) + 86400;
            $where['create_time'] = array('between', [$start_time, $end_time]);
        }
        $where['user_id'] = input('user_id');

        $keywordComplex = [];
        $usersQuery = Db::name('user_center_diagnose');

        $list = $usersQuery->whereOr($keywordComplex)->where($where)->order("create_time DESC")->paginate(15);
        // 获取分页显示
        $list->appends($request);
        $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);
        // 渲染模板输出
        return $this->fetch();
    }

    /**
     * 添加数据
     * @adminMenu(
     *     'name'   => '添加文章',
     *     'parent' => 'index',
     *     'display'=> false,
     *     'hasView'=> true,
     *     'order'  => 10000,
     *     'icon'   => '',
     *     'remark' => '添加文章',
     *     'param'  => ''
     * )
     */
    public function add()
    {
        return $this->fetch();
    }

    /**
     * 添加/编辑数据提交
     * @adminMenu(
     *     'name'   => '添加文章提交',
     *     'parent' => 'index',
     *     'display'=> false,
     *     'hasView'=> false,
     *     'order'  => 10000,
     *     'icon'   => '',
     *     'remark' => '添加文章提交',
     *     'param'  => ''
     * )
     */
    public function addPost()
    {
        $model = Db::name('user_center_diagnose');
        if ($this->request->isPost()) {
            $data = $this->request->param();
            foreach ($data as &$val) {
                if (is_array($val)) {
                    $val = serialize($val);
                }
            }
            $data['update_time'] = time();
            if (empty($data['id'])) {
                $data['admin_id'] = $this->admin_id;
                $data['create_time'] = time();
                $res = $model->insert($data);
                adminLog("添加中心名称及诊断(ID:$res)");
                $this->success('添加成功!', url('CenterDiagnose/index', ['user_id' => $data['user_id']]));
            } else {
                $updata = array(
                    'pd_o'=>0,
                    'pds_o'=>0,
                    'hpds_o'=>0,
                    'msa_o'=>0,
                    'psp_o'=>0,
                    'cbd_cbs_o'=>0,
                    'dlb_o'=>0,
                    'n_pd_o'=>0,
                    'pd_n'=>0,
                    'pds_n'=>0,
                    'hpds_n'=>0,
                    'msa_n'=>0,
                    'psp_n'=>0,
                    'cbd_cbs_n'=>0,
                    'dlb_n'=>0,
                    'n_pd_n'=>0,
                );
                $res0 = $model->where(array('id' => $data['id']))->update($updata);

                $res = $model->where(array('id' => $data['id']))->update($data);
                adminLog("编辑中心名称及诊断(ID:" . $data['id'] . ")");
                $this->success('编辑成功!', url('CenterDiagnose/index', ['user_id' => $data['user_id']]));
            }
        }

    }

    /**
     * @return mixed编辑数据
     */
    public function edit()
    {
        $model = Db::name('user_center_diagnose');
        $id = $this->request->param('id', 0, 'intval');
        $data = $model->find($id);

        $data['old_diagnose'] = unserialize($data['old_diagnose']);
        $data['new_diagnose'] = unserialize($data['new_diagnose']);
        $this->assign('data', $data);
        return $this->fetch();
    }

    /**
     * 删除数据
     * @throws \think\Exception
     */
    public function delete()
    {
        $model = Db::name('user_center_diagnose');
        $param = $this->request->param();
        if (isset($param['id'])) {
            $id = $this->request->param('id', 0, 'intval');
            $result = $model->where(['id' => $id])->find();
            $model->where(['id' => $id])->delete();
            adminLog("删除中心名称及诊断(ID:" . $id . ")");
            $this->success("删除成功！", '');
        }
        if (isset($param['ids'])) {
            $ids = $this->request->param('ids/a');
            $result = $model->where(['id' => ['in', $ids]])->delete();
            adminLog("删除中心名称及诊断(ID:" . implode(",", $ids) . ")");
            if ($result) {
                $this->success("删除成功！", '');
            }
        }
    }
}
